### ISSUE TITLE
line parser string is wrong

### ISSUE THREAD

**Issue by andrius** [xtokio/asterisk#1]
Good afternoon, and than you for referencing me in your repository ;) 
Recently I just got a need to finish the library and I've returned back. AMI, then ARI will be added. If you like to participate/collaborate, welcome! 

Some comments:

Returning events are splitted by ":" but my initial regular expression were incorrect. New one is here: https://github.com/ctiapps/asterisk/blob/develop/src/asterisk/ami.cr#L152, or if you will read data line-by-line, this is better:

```crystal
if /(^[\w\s\/-]*):[\s]*(.*)\r\n$/m =~ line```
```
The way how you do receiving data to merge events: https://github.com/xtokio/asterisk/blob/master/src/asterisk/ami.cr#L84 is not optimal on loaded asterisk, it could cause conflicts. You really shall track track by `actionid`. I think to populate my reworked code very soon!

NOTE: I've created dockerfile and specs to test right agains asterisk, really useful!

**Comment by xtokio** [comment]
This is Awesome! thank you for getting in touch I really appreciate the time you are taking to check my buggy version I'm still new to Crystal but I like it and I will fix my code with your recommendation also I'm working on trying to implement ARI ( I don't know much about docker so I ended up spinning a server on Digital Ocean for testing ) and thanks again.
